const ADD_NUMBER = "ADD_NUMBER";
const SUB_NUMBER = "SUB-NUMBER";
const INCREMENT = "INCREMENT";
const DECREMENT = "DECREMENT";
const CHANGE_BANNERS = "CHANGE_BANNERS";
const CHANGE_RECOMMENDS = "CHANGE_RECOMMENDS";
export {
  ADD_NUMBER,
  SUB_NUMBER,
  INCREMENT,
  DECREMENT,
  CHANGE_BANNERS,
  CHANGE_RECOMMENDS,
};
